#@ load("@ytt:data", "data")
---
#@ if data.values.enableRedisCachingQuoteService:
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ClassClaim
metadata:
  name: quote-cache
  namespace: #@ data.values.namespaceToDeploy
spec:
  classRef:
    name: redis-unmanaged
#@ end
---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: #@ data.values.quoteServiceDeployName
  namespace: #@ data.values.namespaceToDeploy
  #@ if data.values.otelState:
  annotations:
    instrumentation.opentelemetry.io/inject-java: #@ data.values.namespaceToDeploy + "/my-instrumentation"
  #@ end
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: quote-service
    apis.apps.tanzu.vmware.com/register-api: "true"
    #@ if data.values.hasTests:
    apps.tanzu.vmware.com/has-tests: "true"
    #@ end
spec:
  params:
  - name: annotations
    value:
      #@ if data.values.autoScalingClass == "kpa":
      #@ if data.values.autoScalingMinScale:
      autoscaling.knative.dev/minScale: #@ data.values.autoScalingMinScale
      #@ end
      #@ if data.values.autoScalingMaxScale:
      autoscaling.knative.dev/maxScale: #@ data.values.autoScalingMaxScale
      #@ end
      #@ if data.values.autoScalingScaleDownDelay:
      autoscaling.knative.dev/scaleDownDelay: #@ data.values.autoScalingScaleDownDelay
      #@ end
      #@ end

      #@ if data.values.autoScalingClass == "hpa":
      autoscaling.knative.dev/class: hpa.autoscaling.knative.dev
      autoscaling.knative.dev/metric: cpu
      #@ end
  - name: api_descriptor
    value:
      type: openapi
      location:
        path: "/v3/api-docs"
      system: tanzu-banking-system
      owner: bank-team-a
      description: "A set of API endpoints to manage the resources within the quote-service App."
  #@ if data.values.hasTests:
  - name: testing_pipeline_matching_labels 
    value:
      apps.tanzu.vmware.com/pipeline: test
      apps.tanzu.vmware.com/language: java
  - name: scanning_source_policy
    value: scan-policy-relaxed
  - name: scanning_image_policy
    value: scan-policy-relaxed
  #@ end
  #@ if data.values.airgapped:
  - name: buildServiceBindings
    value:
    - kind: Secret
      name: settings-xml
  #@ end
  build:
    env:
    - name: BP_JVM_VERSION
      #@ if data.values.javaVersion == 17:
      value: "17.*"
      #@ end
      #@ if data.values.javaVersion == 11:
      value: "11.*"
      #@ end
  env:
    - name: spring.cloud.config.uri
      value: #@ "http://config-server."+data.values.namespaceToDeploy+".svc.cluster.local"
    #@ if data.values.eurekaState:
    - name: EUREKA_URL
      value: #@ data.values.eurekaURL
    #@ end
    #@ if data.values.otelState:
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: "application=bankingApp"
    #@ end
    #@ if data.values.enableRedisCachingQuoteService:
    - name: spring.cache.type
      value: 'redis'
    #@ end
    #@ if data.values.airgapped:
    - name: AIRGAPPED
      value: "true"
    #@ end
  source:
    git:
      url: #@ data.values.gitRepo
      ref:
        branch: #@ data.values.branchNameQuoteService
    subPath: quote-service
  #@ if data.values.enableRedisCachingQuoteService:
  serviceClaims:
  - name: quote-cache-claim
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ClassClaim
      name: quote-cache
  #@ end