#@ load("@ytt:data", "data")
---
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: my-instrumentation
  namespace: #@ data.values.namespaceToDeploy
spec:
  exporter:
    #@ if data.values.selectTracingMethod == "wavefront":
    endpoint: http://wavefront-proxy.observability-system:4317
    #@ end
    #@ if data.values.selectTracingMethod == "jaeger":
    endpoint: http://jaeger-collector.monitoring:4317
    #@ end
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
---
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: dotnet-instrumentation
  namespace: #@ data.values.namespaceToDeploy
spec:
  exporter:
    #@ if data.values.selectTracingMethod == "wavefront":
    endpoint: http://wavefront-proxy.observability-system:4318
    #@ end
    #@ if data.values.selectTracingMethod == "jaeger":
    endpoint: http://jaeger-collector.monitoring:4318
    #@ end
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio