#@ load("@ytt:data", "data")
---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: #@ data.values.quoteServiceDotnetDeployName
  namespace: #@ data.values.namespaceToDeploy
  #@ if data.values.otelState:
  annotations:
    instrumentation.opentelemetry.io/inject-dotnet: #@ data.values.namespaceToDeploy + "/my-instrumentation"
  #@ end
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: quote-service
    #@ if data.values.hasTests:
    apps.tanzu.vmware.com/has-tests: "true"
    #@ end
spec:
  params:
  - name: annotations
    value:
      #@ if data.values.autoScalingClass == "kpa":
      #@ if data.values.autoScalingMinScale:
      autoscaling.knative.dev/minScale: #@ data.values.autoScalingMinScale
      #@ end
      #@ if data.values.autoScalingMaxScale:
      autoscaling.knative.dev/maxScale: #@ data.values.autoScalingMaxScale
      #@ end
      #@ if data.values.autoScalingScaleDownDelay:
      autoscaling.knative.dev/scaleDownDelay: #@ data.values.autoScalingScaleDownDelay
      #@ end
      #@ end

      #@ if data.values.autoScalingClass == "hpa":
      autoscaling.knative.dev/class: hpa.autoscaling.knative.dev
      autoscaling.knative.dev/metric: cpu
      #@ end
  #@ if data.values.hasTests:
  - name: testing_pipeline_matching_labels 
    value:
      apps.tanzu.vmware.com/pipeline: test
      apps.tanzu.vmware.com/language: dotnet
  - name: scanning_source_policy
    value: scan-policy-relaxed
  - name: scanning_image_policy
    value: scan-policy-relaxed
  #@ end
  #@ if data.values.airgapped:
  - name: buildServiceBindings
    value:
    - kind: Secret
      name: nugetconfig
  #@ end
  env:
    - name: ASPNETCORE_ENVIRONMENT
      value: Development
    - name: ASPNETCORE_URLS
      value: http://0.0.0.0:8080;http://0.0.0.0:8090
    - name: Management__Port
      value: "8080"
    - name: eureka__client__serviceUrl
      value: #@ data.values.eurekaURL
    #@ if data.values.otelState:
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: "application=bankingApp"
    #@ end
    #@ if data.values.airgapped:
    - name: AIRGAPPED
      value: "true"
    #@ end
  #@ if data.values.quoteServiceDotnetTilt:
  image: #@ data.values.containterRegistryURL + "/" + data.values.quoteServiceDotnetDeployName + "-dev"
  #@ end
  source:
    git:
      url: #@ data.values.gitRepo
      ref:
        branch: #@ data.values.branchNameQuoteServiceDotnet
    subPath: quote-service-dotnet
