#@ load("@ytt:data", "data")
---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: discovery-server
  namespace: #@ data.values.namespaceToDeploy
  #@ if data.values.otelState:
  annotations:
    instrumentation.opentelemetry.io/inject-java: #@ data.values.namespaceToDeploy + "/my-instrumentation"
  #@ end
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: discovery-server
    #@ if data.values.hasTests:
    apps.tanzu.vmware.com/has-tests: "true"
    #@ end
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  #@ if data.values.hasTests:
  - name: testing_pipeline_matching_labels 
    value:
      apps.tanzu.vmware.com/pipeline: test
      apps.tanzu.vmware.com/language: java
  - name: scanning_source_policy
    value: scan-policy-relaxed
  - name: scanning_image_policy
    value: scan-policy-relaxed
  #@ end
  #@ if data.values.airgapped:
  - name: buildServiceBindings
    value:
    - kind: Secret
      name: settings-xml
  #@ end
  build:
    env:
    - name: BP_JVM_VERSION
      value: "17.*"
  env:
    - name: spring.cloud.config.uri
      value: #@ "http://config-server."+data.values.namespaceToDeploy+".svc.cluster.local"
    #@ if data.values.otelState:
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: "application=bankingApp"
    #@ end
  source:
    git:
      url: #@ data.values.gitRepo
      ref:
        branch: #@ data.values.branchNameDiscoveryServer
    subPath: discovery-server
